AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaJSONDataToS3:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 20
      FunctionName: sapRfcReadTableToS3
      Handler: index.handler
      Runtime: nodejs10.x
      Policies: 
        - AWSLambdaExecute
        - AmazonS3FullAccess
        - AmazonKinesisFirehoseFullAccess